### ISSUE TITLE
Error in process_bwt

### ISSUE THREAD

**Issue by gis-ooiwf** [HansenHeLab/sgTiler#1]
Hi,
 I ran sgTiler and encounter the error below with the following command and content:

**The command as below:**
python sgTiler.py -i ../data/input/Ch1-45240909-45241309.txt --bowtie-index /home/ubuntu/bowtie/indexes/hg19 --gtf ../data/input/allExons.sorted.merged.bed  --sg-expected 8 --verbose --dir ../data/output --dir ../data/output --output sgTiler_output

**The content of the fa ("Ch1-45240909-45241309.txt") is:**
>hg19_dna range=chr14:38064039-38064439 5'pad=0 3'pad=0 strand=+ repeatMasking=lower
CCCCGGCCTCCCCCGGCACGGGCTCCAGCGGCGCCCCACCGGCCGCCCGC
CTCGCCTTGCCTCTCACCTCCTGCGTGTCTGCGTAGTAGCTGTTCCAGTC
GCTGGTTTCATGCCCTTCCATCTTCACAGTTCCTAACATCCTGGAGCCAC
CCTGCCCAATACAACCATCCAGCCCTGTGCGAAGCGAcgggcggccgcgc
ggcgcggggcgggggAGGGGAGCTGAGCAGCTGCAGTCACCCGAGCGCCC
GCGCGGGCCCAACGCCACCCGGGCGAAGAGGAAGCCCAGAGCTgcggggc
gcggcgtgcgcggcggcggcggcggcgcggcgggcgggggcagcgccggg
ggcaggcggctgccgcggagcgcggcgccggGGAGCGCCTCCGCGGGAAG

**The error:**
Traceback (most recent call last):
  File "sgTiler.py", line 579, in <module>
    main()
  File "sgTiler.py", line 530, in main
    process_bwt(input_seqs, args.output + '_sgrna.filtered' + '.align.bwt', gtf,dhs)
  File "sgTiler.py", line 312, in process_bwt
    if words[0] not in input_seqs[ids[0]]['sgRNAs']:
KeyError: 'hg19'

**Comment by halffedelf** [comment]
Hi, you're input fasta file is not in the proper format. The header line in the fasta file should start with ">". E.g.,
```
>chr14:38064039-38064439
CCCCGGCCTCCCCCGGCACGGGCTCCAGCGGCGCCCCACCGGCCGCCCGC
CTCGCCTTGCCTCTCACCTCCTGCGTGTCTGCGTAGTAGCTGTTCCAGTC
GCTGGTTTCATGCCCTTCCATCTTCACAGTTCCTAACATCCTGGAGCCAC
CCTGCCCAATACAACCATCCAGCCCTGTGCGAAGCGAcgggcggccgcgc
ggcgcggggcgggggAGGGGAGCTGAGCAGCTGCAGTCACCCGAGCGCCC
GCGCGGGCCCAACGCCACCCGGGCGAAGAGGAAG
```

Also, please note the updated README. It is in much more details now.
Please let me know if this resolves the issue so I can close it.
